### PR TITLE
minor heartbeat/tests related tasks #65

### LINKED ISSUE #61: tests: some of the misbehavior cases should test if the misbehavior is detected correctly
e.g. 

- the wrong sig test should ensure the validator detects this as wrong sig
- same for deceptive stateRoot and an invalid state transition

in order to do that, consider a new, non-propagated validatorMessage, specifically for this

related to #65

### PR DESCRIPTION
**Pull request by samparsky**
Fixes #61 #65 
- [x] getLatestMsg - SHOULD RELY ON PROPER TIMESTAMP/SEQUENCE; maybe a primitive DB abstraction?
- [x] https://github.com/AdExNetwork/adex-validator-stack-js/issues/61
- [x] those tests should be more robust - and rely on some feedback messages from the validator stack #61 - perhaps `InvalidNewState` message
- [x] split tests in multiple files
- [ ] decrease repetitiveness in tests (DRY)
- [ ] ~~try to decrease waitTime/propagation logs~~ - leave this for later
- [x] tests: go through each one, try to break them by touching the code

### CODE REVIEW

File: services/validatorWorker/lib/index.js [hunk 1]
```diff
@@ -62,4 +62,48 @@ function toBNStringMap(raw){
...
+function invalidNewState(channel, adapter, { reason, newMsg}) {
+	// quirk: type is overiding type in newMsg
+	return persist(adapter, channel, {
+		...newMsg,
+		type: 'InvalidNewState',
+		reason,
+	})
+}
+
+function onError(channel, adapter, { reason, newMsg, prevBalances, newBalances }) {
```
Comment (Ivshti) [inline services/validatorWorker/lib/index.js]: I'm pretty sure you don't need the balances here. For testing purposes, we only need to detect if the error type is the right one

File: services/validatorWorker/lib/index.js [hunk 2]
```diff
@@ -62,4 +62,48 @@ function toBNStringMap(raw){
 	return balances
 }
 
-module.exports = { getStateRootHash, isValidRootHash, toBNMap, getBalancesAfterFeesTree, toBNStringMap }
+function toStringBN(raw) {
```
Comment (Ivshti) [inline services/validatorWorker/lib/index.js]: if you drop prev balances/nextbalances, then this can be dropped too

File: services/validatorWorker/follower.js [hunk 3]
```diff
@@ -97,7 +128,7 @@ function getLatestMsg(channelId, from, type) {
 		from: from,
 		'msg.type': type,
 	})
-	.sort({ _id: -1 })
+	.sort({ 'msg.created': -1 })
```
Comment (Ivshti) [inline services/validatorWorker/follower.js]: great! I think there one "@TODO" comment that can be deleted because this is fixed now

File: services/validatorWorker/follower.js [hunk 4]
```diff
@@ -56,16 +71,31 @@ function onNewState(adapter, {channel, balances, newMsg, approveMsg}) {
...
 		if (!isValidSig) {
-			console.error(`validatatorWorker: ${channel.id}: invalid signature NewState`, prevBalances, newBalances)
-			return { nothingNew: true }
+			return onError(
+				channel,
+				adapter,
+				{
+					reason: `InvalidSignature`,
+					newMsg,
+					prevBalances,
```
Comment (Ivshti) [inline services/validatorWorker/follower.js]: again, without prevbalances/newbalances, this can become much simpler

File: services/validatorWorker/follower.js (hunk 3 above)
Comment (samparsky) [reply services/validatorWorker/follower.js]: its deleted
