### PR TITLE
fix: state sign

### LINKED ISSUE #52: critical: signed state roots do not comply with protocol
the protocol defines what's being signed as a `keccak256(channelId, balanceRoot)` but currenly we only sign `balanceRoot`

see https://github.com/AdExNetwork/adex-protocol/blob/master/OUTPACE.md#specification
and https://github.com/AdExNetwork/adex-protocol-eth/blob/master/contracts/AdExCore.sol#L73

### PR DESCRIPTION
**Pull request by samparsky**
Fixes #52

### CODE REVIEW

File: services/validatorWorker/leader.js [hunk 1]
```diff
@@ -17,7 +20,15 @@ function afterProducer(adapter, {channel, newStateTree, balances}) {
 		acc => adapter.getBalanceLeaf(acc, balances[acc])
 	)
 	const tree = new adapter.MerkleTree(elems)
-	const stateRootRaw = tree.getRoot()
+	const balanceRoot = tree.getRoot()
+
+	// keccak256(channelId, balanceRoot)
+	const stateRootRaw = new Buffer(
+		keccak256.arrayBuffer(
+			abi.rawEncode(['bytes', 'bytes'], channel['id'], balanceRoot)
```
Comment (Ivshti) [inline services/validatorWorker/leader.js]: why not `channel.id`?

File: services/validatorWorker/leader.js [hunk 2]
```diff
@@ -1,4 +1,7 @@
 const { persistAndPropagate } = require('./lib/propagation')
+const keccak256 = require("js-sha3").keccak256
```
Comment (Ivshti) [inline services/validatorWorker/leader.js]: inconsistent quotes - we use single quote

File: services/validatorWorker/leader.js [hunk 3]
```diff
@@ -17,7 +20,15 @@ function afterProducer(adapter, {channel, newStateTree, balances}) {
 		acc => adapter.getBalanceLeaf(acc, balances[acc])
 	)
 	const tree = new adapter.MerkleTree(elems)
-	const stateRootRaw = tree.getRoot()
+	const balanceRoot = tree.getRoot()
```
Comment (Ivshti) [inline services/validatorWorker/leader.js]: rather than importing `keccak256`, why don't we just add to the adapter `adapter.getSignableRoot` that would be invoked like `adapter.getSignableRoot(channel, tree.getRoot())` 

this keeps the follower/leader code generic, and allows us to later add more stuff from `channel` into the signable root

File: services/validatorWorker/leader.js (hunk 1 above)
Comment (samparsky) [reply services/validatorWorker/leader.js]: ok, will change it to that

File: services/validatorWorker/leader.js (hunk 3 above)
Comment (samparsky) [reply services/validatorWorker/leader.js]: ok making the change

File: adapters/dummy/index.js [hunk 4]
```diff
@@ -26,6 +26,10 @@ function getBalanceLeaf(acc, bal) {
 	return Channel.getBalanceLeaf(acc, bal)
 }
 
+function getSignableStateRoot(channel, balanceRoot) {
```
Comment (Ivshti) [inline adapters/dummy/index.js]: should be channelId; in the other adapter too
